# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Fz Blog 
subtitle: 长路漫漫，唯剑作伴
author: 方志
language: 
timezone: 

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url:  https://fangzhioo.github.io/   # Note: don't forget to modify the CNAME file to your url
root: /
#permalink: :year/:month/:day/:title/
permalink: :category/:title/
permalink_defaults:
  lang: en

#Custom Setting Start

# Site settings
SEOTitle: 方志 | Blog
email: fangzhioooo@gmail.com
description: "死亡如风，常伴吾身~"
keyword: "方志, fangzhioo, Fz Blog, 博客, 个人网站, 互联网, Web, JavaScript, 前端, 设计"
header-img: /img/header_img/home.jpg
article-img: /img/article_header/article_bg.jpg
404-img: /img/header_img/404.png
signature: false  #show signature
signature-img: img/signature/fangzhi.png 



# 设置nav排序
nav_menu: [
    {
        title: "About",
        href: "/about/"
    },
    {
        title: "Archives",
        href: "/archive/"
    }
    ,
    {
        title: "Tags",
        href: "/tags/"
    }
]


# SNS settings
# RSS: false
weibo_username:     fangzhioooo
zhihu_username:     fang-zhi-4-73
github_username:    fangzhioo
# twitter_username:   Demonbane_x
# facebook_username:  xxx
# linkedin_username:  xxx

# Build settings
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`


# Disqus settings 碍于需要翻墙 暂时屏蔽了
# disqus_username: fangzhioo

# 来必力  国内暂时没有被墙
livere_uid: MTAyMC80Mzg3OC8yMDQxMw==

# Analytics settings
#Baidu Analytics
# ba_track_id: xxx
# Google Analytics
ga_track_id: 'UA-138588101-1'          # Format: UA-xxxxxx-xx
ga_domain: fangzhi.ml


# Sidebar settings
sidebar: true                       # whether or not using Sidebar.
sidebar-about-description: "且随疾风前行，身后亦须留心。"
sidebar-avatar: /img/avatar/yasuo.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`
widgets:
- featured-tags
- short-about
- recent-posts
- friends-blog
- archive
- category

# widget behavior
## Archive
archives-img: /img/header_img/archives-widget.jpg
archive_type: 'monthly'
show_count: true


## Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

## Friends
friends: [
    {
        title: "Bean Tech",
        href: "http://beantech.org/"
    }
]

#Custom Setting End



# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: article
category_map:
  Docker: docker
  Golang: golang
  Nginx: nginx
  Database: database
  Web: web

tag_map:
home_posts_tag: true # show posts tags

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: archives

archive_generator:
  per_page: 10
  yearly: true
  monthly: true
  daily: false
  
# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
  
# Extensions
## Plugins: https://hexo.io/plugins/

# recommended-posts
# reference: https://github.com/huiwang/hexo-recommended-posts
# recommended_posts:
#   server: https://api.truelaurel.com #后端推荐服务器地址
#   timeoutInMillis: 10000 #服务时长，超过此时长，则使用离线推荐模式
#   internalLinks: 3 #内部文章数量
#   externalLinks: 0 #外部文章数量
#   autoDisplay: true, #自动在文章底部显示推荐文章
#   titleHtml: <h2>推荐文章<span style="font-size:0.45em; color:gray"></span></h2> #自定义标题

# hexo-tag-aplayer
# reference: https://github.com/MoePlayer/hexo-tag-aplayer
# aplayer:
#   meting: true

# MeingJS support for Aplayer 音乐播放器
# reference: https://github.com/metowolf/MetingJS & https://github.com/MoePlayer/APlayer
metingjs: true
data-id: 2297428102     # 歌曲/专辑/歌单对应的id。（必须）注意这里需要是歌曲原本的id,不是你自己歌单中点击后显示的。 
data-server: netease    # 音乐平台 （必须）netease(网易云音乐) tecent(qq音乐) xiami(虾米音乐) kugou(酷狗音乐) 。
data-type: playlist     # 请求类型 （必须）song(单曲) album(专辑) playlist(歌单) search(搜索)
data-fixed: true
  # data-mini:
  # data-autoplay:    

# Live2D
## https://github.com/xiazeyu/live2d-widget.js
## https://github.com/EYHN/hexo-helper-live2d/blob/master/README.zh-CN.md
## https://l2dwidget.js.org/docs/class/src/index.js~L2Dwidget.html#instance-method-init
live2d:
  enable: true
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: true
  debug: false
  model:
    # use: live2d-widget-model-shizuku
    use: kanna
    position: right
    width: 280
    height: 335
  mobile:
    show: true
  react:
    opacity: 0.7

# Reward  赞赏
reward: true
reward_comment: 赞赏一下
wechatpay: /img/reward/wechat_pay.jpg
alipay: /img/reward/alipay.jpg

# busuanzi  统计次数
busuanzi: true

# Share 分享
# Reference: https://github.com/overtrue/share.js
share: true

## Themes: https://hexo.io/themes/  对应themes文件夹下的目录
theme: fangzhioo

#sitemap
sitemap:
  path: sitemap.xml

# Deployment
## Docs: https://hexo.io/docs/deployment.html
# repository: https://github.com/fangzhioo/fangzhioo.github.io.git
# branch: master
deploy:
  type: git
  repository: https://github.com/fangzhioo/fangzhioo.github.io
  branch: master
  message: Create Code

# toc 
## Docs: https://github.com/bubkoo/hexo-toc
toc:
  maxDepth: 3
  slugify: transliteration